HomeWork5
VictorTuricenco/VICTOR_TURICENCO pull request #6
Opened 2023-04-04 18:05 UTC by VictorTuricenco

2023-04-06 16:55 UTC, gh3rtzz commented on src/main/java/org/example/homework_nr_5/Weekday.java
> +//    public boolean isWeekday() {
remove this comment if you do not need it

2023-04-06 16:56 UTC, gh3rtzz requested changes
remove unnecessary comments

2023-04-06 19:31 UTC, VictorTuricenco commented
> remove unnecessary comments

Done as requested

2023-04-09 11:17 UTC, gh3rtzz approved these changes
approved

2023-04-09 11:38 UTC, merged